---
title: "Life history of the common blacktip shark, *Carcharhinus limbatus*, from central eastern Australia and comparative demography of a cryptic shark complex"
author: |
    | Alastair V Harry$^{A,B,G}$, Paul A Butcher$^C$, William G Macbeth$^D$, Jess AT Morgan$^E$, Stephen M Taylor$^B$, Pascal T Geraghty$^F$
    |
    | $^A$Centre for Sustainable Tropical Fisheries & Aquaculture, College of Marine & Environmental Sciences, James Cook University, Townsville, QLD, 4811, Australia
    | $^B$Department of Primary Industries and Regional Development, PO Box 20, North Beach, WA, 6920, Australia
    | $^C$Department of Primary Industries, New South Wales Fisheries, PO Box 4321, Coffs Harbour, NSW 2450, Australia
    | $^D$FERM Services, PO Box 337, Sheffield, TAS, 7306, Australia
    | $^E$Molecular Fisheries Laboratory, School of Biomedical Sciences, The University of Queensland, St. Lucia, Queensland 4072, Australia
    | $^F$Roads and Maritime Services, 33 James Craig Road, Rozelle Bay, NSW, 2039, Australia
    | $^G$Corresponding author: alastair.harry@gmail.com
    | *Running title: Biology and comparative demography of Carcharhinus limbatus*
output: 
  pdf_document:
    latex_engine: "pdflatex"
    keep_tex: true
  word_document:
    keep_md: false
linestretch: 2 
csl: "../references/international-journal-of-wildland-fire.csl"
bibliography: "../references/blacktip.bib"
header-includes:
    - \fontsize{12}{20}
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \fancyhf{}
    - \fancyfoot[L]{\thepage}
    - \renewcommand{\headrulewidth}{0pt}
    - \renewcommand{\footrulewidth}{0pt}
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE, echo=FALSE}
# Load results
source(here::here("analysis", "load_results.R"))

## Summary tables refered to in inline code chunks

nsw_sex_ratio <- colSums(table(data$Source, data$Sex)[c(3, 4), ])
depth_max <- tapply(data$Depth, data$Sex, max, na.rm = T)

# Ageing stats
age_bias <- ageBias(Reader1 ~ Reader2, floor(age))
age_precision <- agePrecision(Reader1 ~ Reader2, floor(age))
age_stats <- age_dat %>%
  group_by(Sex) %>%
  summarise(
    n = n(), minSTL = min(STL), maxSTL = max(STL),
    minAge = min(AgeAgree), maxAge = max(AgeAgree)
  )

# Length weight analysis
weight_stats <- select(data, Wgt, STL, Sex) %>%
  group_by(Sex) %>%
  na.omit() %>%
  summarise(n = n(), maxWgt = max(Wgt), maxSTL = max(STL))

# Female maturity stats
female_mat_stats <- filter(data, Sex %in% "Female", !is.na(Uter.stage)) %>%
  select(STL, AgeAgree, Mat, Uter.stage) %>%
  group_by(Uter.stage) %>%
  summarise(
    n = n(), minSTL = min(STL, na.rm = T), maxSTL = max(STL, na.rm = T),
    minAge = min(AgeAgree, na.rm = T), maxAge = max(AgeAgree, na.rm = T)
  )

# Male maturity stats
male_mat_stats <- filter(data, Sex %in% "Male", !is.na(Clasp.calc)) %>%
  select(STL, AgeAgree, Mat, Clasp.calc) %>%
  group_by(Clasp.calc) %>%
  summarise(
    n = n(), minSTL = min(STL), maxSTL = max(STL),
    minAge = min(AgeAgree, na.rm = T), maxAge = max(AgeAgree, na.rm = T)
  )

# Mean weight at birth
L0_weight <- filter(data, Umb.Scar %in% c("y", "p")) %>%
  filter(!is.na(Wgt)) %>%
  summarise(mean_Wgt = mean(Wgt, na.rm = T), sd_Wgt = sd(Wgt, na.rm = T), n = n())

# Pregnant female stats
pregnant <- filter(data, Uter.stage %in% "E") %>%
  select(Date, STL, Emb, EmbTL, Comments = Sex.Ratio.M.F)

tcrit <- qt(1 - 0.05 / 2, lw_both$model$df.residual)

# Maturity
largest <- predict(lw_both$model, newdata = data.frame(`STL` = max(data$STL, na.rm = T)), se.fit = T)
largest_upper <- exp(largest$fit + sqrt(largest$se.fit^2 + summary(lw_both$model)$dispersion) * tcrit) %>% round()
largest_lower <- exp(largest$fit - sqrt(largest$se.fit^2 + summary(lw_both$model)$dispersion) * tcrit) %>% round()

# R intrinsic
r_int_lim <- filter(demog_summary, species %in% "C. limbatus") %>% select(r_int_mean)
r_int_lim_ci <- filter(monte_carlo, species %in% "C. limbatus") %>%
  select(r_int) %>%
  summarise(upper = quantile(r_int, 0.975), lower = quantile(r_int, 0.025)) %>%
  round(2)
r_int_til_nt <- filter(demog_summary, species %in% "C. tilstoni (NT)") %>% select(r_int_mean)
r_int_til_qld <- filter(demog_summary, species %in% "C. tilstoni (QLD)") %>% select(r_int_mean)

# R instrinsic bounds
r_int_bounds <- filter(m_r_int, species %in% "C. limbatus") %>%
  select(r_int) %>%
  summarise(r_int = max(r_int))
r_int_bounds_biennial <- r_int_bounds$r_int %>% max() %>% round(2)
r_int_bounds_triennial <- r_int_bounds$r_int %>% min() %>% round(2)

# Mortality
m_ratios <- group_by(monte_carlo, species) %>%
  mutate(ratio = exp(-M_m) / exp(-M_f)) %>%
  select(M_m, M_f, ratio) %>%
  summarise(ratio = mean(ratio)) %>%
  mutate(percents = round(100 * (1 - ratio), 0))
```

\newpage

### Abstract
Common and Australian blacktip sharks (*Carcharhinus limbatus* and *Carcharhinus tilstoni*) occur sympatrically in Australia where they are reported as a complex due to their morphological similarities. This study provides the first description of the life history of *C. limbatus* using samples from central eastern Australia, where *C. tilstoni* is rare. Females (`r min(data$STL[data$Sex == "Female"], na.rm = T) %>% round()` - `r max(data$STL[data$Sex == "Female"], na.rm = T)` cm TL, *n* = `r table(data$Sex)[1]`) and males (`r min(data$STL[data$Sex == "Male"]) %>% round()` - `r max(data$STL[data$Sex == "Male"])` cm TL, *n* = `r table(data$Sex)[2]`) both matured at 8.3 years and 200 cm TL, which exceeds the maximum length of *C. tilstoni*. Vertebral ageing revealed that female and male *C. limbatus*  lived to `r round(age_stats$maxAge) %>% min` and `r round(age_stats$maxAge) %>% max` years, respectively, exceeding known longevity in *C. tilstoni*. The intrinsic rate of population increase, *r*, calculated using a Euler-Lotka demographic method was `r demog_summary$r_int_mean %>% min` (`r round(demog_summary$r_int_sd %>% min, 2)`) yr$^{-1}$ for *C. limbatus*, compared to `r demog_summary$r_int_mean %>% median` (`r round(demog_summary$r_int_sd %>% median, 2)`) and `r formatC(demog_summary$r_int_mean %>% max, format = "f", flag = "0", digits = 2)` (`r round(demog_summary$r_int_sd %>% max, 2)`) yr$^{-1}$ for two *C. tilstoni* stocks. Despite their similar appearance, these species differed in both their biological productivity and susceptibility to fishing activities. Monitoring of relative abundance should be a priority given they are likely to have divergent responses to fishing. 

**Additional keywords:** age and growth, reproductive biology, Chondrichthyes, fisheries management

\newpage


## Introduction

Cryptic species complexes pose many challenges for fisheries management and biodiversity conservation. These are particularly evident in the morphologically conservative class of chondrichthyan fishes where a taxonomic rennaissance in recent years has revealed high cryptic biodiversity [@marshall_redescription_2009; @ebert_resurrection_2010; @white_review_2012; @quattro_sphyrna_2013]. By virtue, the discovery of a complex violates the assumption that the species is a single unit for management purposes, often with important consequences. For example, declines in the Critically Endangered common skate, already one of the best documented examples of near-extinction of a marine fish [@brander_disappearance_1981; @dulvy_fishery_2000], might have masked greater declines in the larger and more intrinsically susceptible flapper skate, *Dipturus intermedius* [@iglesias_taxonomic_2010]. Similarly, it is likely that the California butterfly ray, *Gymnura marmorata*, has a more restricted and fragmented range than previously thought as a result of historical misidentification with the morphologically similar and sympatric Mazatlan butterfly ray, *Gymnura crebripuncata* [@smith_morphometric_2009]. If hybridisation is occuring, the productivity of a fish stock can also be reduced if hybrid fitness is low and hybridisation common [@hatfield_ecological_1999].  

Australia's blacktip shark complex is another case that highlights the difficulties associated with morphologically similar, co-occurring sharks and rays. Study of this species complex over the past four decades has left a confusing body of scientific literature that obstructs effective management. The complex consists of two species; the Australian blacktip, *Carcharhinus tilstoni*, a shark endemic to inshore coastal waters of northern Australia, and the more widely distributed common blacktip, *Carcharhinus limbatus*, a shark found throughout inshore tropical and subtropical waters globally. Whitley's [-@whitley_new_1950] initial account of *C. tilstoni* described the shark as a new species, but stated that it differed only from *C. limbatus* in its dentition. Subsequent taxonomic studies concluded it was a synonym of *C. limbatus*, a species that varies in many aspects of its morphology across its range [@garrick_sharks_1982; @compagno_sharks_1988].

When Australia's northern shark resources developed during the 1970s, *C. limbatus* was initially thought to be the largest single component of the catch in a Taiwanese surface gillnet fishery that retained over 20 000 tonnes per year of pelagic fish and sharks from the Arafura and Timor Seas [@millington_prospects_1981; @lyle_mercury_1984]. The proclamation of the Australian Fishing Zone brought this fishery under Australian jurisdiction in 1979 and research surveys revealed that the main target shark species was actually comprised of two distinct groups of individuals separable by clasper lengths, vertebral counts, and pelvic fin colouration [@stevens_biology_1986]. The smaller maturing, and far more common of these two groups was resurrected as *C. tilstoni* [@stevens_biology_1986]. The other, much rarer group, which had dark pelvic fin markings and was seemingly present in only negligible quantities (a 1 to 300 ratio), was confirmed genetically to be the true *C. limbatus* [@lavery_genetic_1991]. 

The perception that *Carcharhinus limbatus* was a minor component of shark landings continued until the late 2000s (Last and Stevens 2009) when a survey using mitochondrial DNA (mtDNA) sequences unexpectedly found it to be present in quantities equal to *C. tilsoni* [@ovenden_towards_2010]. At around the same time, another study using mtDNA taken from samples from temperate latitudes on the east coast recorded a southward range expansion in excess of 1000 km for *C. tilstoni*, challenging the perception that the species was confined to the tropics [@boomer_genetic_2010]. However, the validity of these findings was brought into doubt when a mismatch between vertebral counts and mtDNA species identity was found in Queensland blacktips [@harry_comparison_2012]. This mismatch extended to various other morphological and ecological characteristics of both species, including body size, maturity, length at birth, and timing of birth. Investigation of nuclear markers revealed this discordance to be the result of hybridisation between the two species [@morgan_detection_2012]. More recent research indicates that hybrids are introgressed and likely the result of ancestral interbreeding between the two species (J.A.T. Morgan, unpublished data).

Despite several decades of research on blacktip sharks in Australia, considerable uncertainty remains over the range of both species, aspects of their ecology, the impact of historical overfishing [@walters_shark_1997; @field_changes_2012], and their relative abundances and ratios in the multiple commercial fisheries in which they are captured [@harry_evaluating_2011; @tillett_accuracy_2012]. One major obstacle to progress has recently been resolved with the discovery that pelvic fin markings can be used to discriminate between the two species with 90% accuracy [@johnson_novel_2017]. Another major issue that remains unaddressed is the absence of baseline life history data for *C. limbatus* from Australian waters. An understanding of its life history is needed to determine the relative productivity of this species and its suceptibility to fishing. It is also required to help provide a clear picture of the ecological role this species plays. It has generally been accepted that the larger *C. limbatus* is likely to be more intrinsically susceptible to fishing than *C. tilsoni* [@bradshaw_more_2013]. However, with no practical way to distinguish between them in catches until now and limited knowledge of the biology of *C. limbatus*, they are reported together, and effectively managed as a combined taxonomic category in all fisheries that catch them. 

This study provides the first detailed account of the life history of *C. limbatus* in Australian waters. It is based on data obtained from multiple sources off the central east coast of Australia, where *C. tilstoni* is largely or completely absent. The size, growth, maturity, and reproductive biology are compared with those of *C. tilstoni* from previous studies in the northeastern state of Queensland (Qld) [@harry_age_2013] and the Northern Territory (NT) [@stevens_biology_1986; @davenport_age_1988]. Using demographic analyses we examine differences in stock productivity and resilience to fishing of sympatric blacktip sharks and discuss the management implications for this species complex. 

## Materials and Methods

### Reconstruction of *C. limbatus* life history
The life history of *C. limbatus* was reconstructed using samples synthesised from four predominantly fishery-dependent sources from southeast Qld and northern New South Wales (NSW) (Fig. 1). These were: two observer surveys of the NSW Ocean Trap & Line Fishery (OTLF) carried out between 2008 and 2010 [@macbeth_observer-based_2009] and in 2013 [@broadhurst_temporal_2014]; a 2004 to 2007 study of the shark fauna of Moreton Bay involving both fishery-independent sampling and a commercial fisher from the East Coast Inshore Finfish Fishery (ECIFF) [@taylor_size_2013]; and a sample of neonate sharks purchased from the same fisher in 2007 used to count pre-caudal vertebrae [@harry_comparison_2012]. 

Both the OTLF and ECIFF are multi-sector, multi-gear fisheries, and a description of their characteristics is given in each of the respective studies above. In summary, samples from the OTLF were predominantly obtained from vessels targeting large sharks (> 2 m total length) for their fins using demersal setlines, whereby multiple hooks were attached to a horizontally-set, weighted ground line in waters 5 to 250 m depth [@macbeth_observer-based_2009]. Sampling occurred in NSW coastal waters between $28^\circ 04'S$ (just north of Tweed Heads) and $34^\circ 03'S$ (Sydney). Samples from the ECIFF were obtained from a commercial vessel targeting smaller sharks (< 1.5 m) and teleosts for their flesh in shallow (< 2 m depth), estuarine habitats of Moreton Bay using 700 - 800 m of small-mesh (7.6 - 15.2 cm) gillnet. 

Total length (TL) in cm was measured by placing the shark ventral side down with the upper lobe of the caudal fin depressed in line with the body axis. All further references to length throughout are in TL or have been converted to TL (see Supplementary Material). Body mass was measured to the nearest kilogram in sharks from NSW and nearest 0.1 kg in those from Qld. Sex was determined based on the presence of claspers on males, and outer clasper length (CL) was measured to the nearest mm between the point of the pelvic fin insertion and the tip of the clasper [@compagno_sharks_1984]. In Qld the presence of an unhealed umbilical scar was also recorded to determine size and timing of birth. A section of 3 to 5 vertebrae was sampled from the cervical region of each vertebral column for age determination. 

Sampling techniques were comparable for each of the four data sources, although due to the fishery-dependent nature of most sampling it was seldom possible to measure all variables for each individual. In particular, vertebrae were only collected from the first OTLF survey from 2008 to 2010, while weight data were primarily collected during the second OTLF survey in 2013. 

The species identity of all individuals sampled from NSW between 2008 and 2010 (Fig. 1) was determined using mitochondrial (mtDNA) and nuclear (nDNA) genotyping [@morgan_mitochondrial_2011; @morgan_detection_2012]. Although Taylor *et al.* [-@taylor_size_2013] did not confirm the identity of samples using vertebral counts or molecular methods, Harry *et al.* [-@harry_comparison_2012] found only a single *C. tilstoni* among a sample of 100 individuals from the same location. All unidentified individuals were assumed to be *C. limbatus*. 

### Age determination and growth analysis
Age was determined by counting concentric pairs of hypo- and hyper-mineralised growth zones on thin-sections of vertebrae centra. Ageing was conducted simultaneously with three other large carcharhinid species also captured in the OTLF and a full description of ageing protocols is given in Geraghty *et al.* [-@geraghty_age_2013]. Ageing data for *Carcharhinus limbatus* were withheld from that publication due to uncertainty about the effects of hybridisation with *C. tilstoni* [@morgan_detection_2012]. 

Unstained, sectioned centra were aged twice under a microscope using transmitted light by two readers independently without knowledge of size, sex, or date of capture. *Carcharhinus limbatus* has a synchronous reproductive cycle in the region (see below), enabling partial ages to be assigned subject to the assumptions that all growth zones represented annual increments and the population birth date was 1st November (see Results). Within and between reader ageing bias was investigated graphically using age-bias plots and statistically using Bowker's test of symmetry [@hoenig_analyzing_1995]. Precision and reproducibility in ageing was determined by calculating the coefficient of variation of ageing error [@ogle_fsa:_2017]. 

Growth was modelled using a sex-structured von Bertalanffy model extended to explicitly include ageing error as a random effect, describe variability in growth and length observation error, and incorporate additional information on length at birth. The model described by Cope and Punt [-@cope_admitting_2007] was used as the basis for this approach. This assumes that observed length at age, $l_{i,g}$ for individual *i* of sex $g$ can be described as: $$l_{i,g} = L_{i,g} + \epsilon \quad\quad \epsilon \sim N(0,\sigma_{L,i,g}^2)$$ where $L_{i,g}$ is the sex-specific expected length at age, calculated using a three parameter von Bertalanffy function, modified to incorporate length at birth: $$L_{i,g}(a) = L_0 + (L_{\infty,g}-L_0)(1-e^{-K_{g}\cdot a_{i,g}})$$ where $L_\infty$ is asymptotic length, $L_0$ is length at birth, $K$ is the growth coefficient, and $a_{i,g}$ is true age. Finally $\sigma_{L,i,g}$ is the standard deviation of the normally distributed process error. $L_\infty$ and $K$ were assumed to be different for males and females, given that size differences between sexes are well-documented for this genus, while $L_0$ and $\sigma_{L,i,g}$ were assumed to be the same for both sexes. As per Cope and Punt [-@cope_admitting_2007], the coefficient of variation of the process error, $CV_L$ was assumed to be proportional to length, such that for any individual $\sigma_{L,i,g} = CV_L L_{i,g}$. That is, there is more individual variability in length at age for larger sharks. 

Ageing error caused by the inconsistent interpretation of growth zones by different readers was explicitly incorporated in the model as a random effect by assuming that observed ages and true ages were linked through the following relationship: $$A_{i,j} = a_i + \epsilon_{a,ij} \quad \quad \epsilon_{a,ij} \sim N(0,\sigma_{a,i}^2)$$ where $A_{i,j}$ is the observed age of individual *i* by reader *j*, $a_i$ is true age, and $\sigma_{a,i}$ is the standard deviation of ageing error. The coefficient of variation of ageing error was assumed to be constant, such that, for any individual $\sigma_{a,i} = CV_{a}a_i$, with $CV_a$ calculated outside the model and approximated by the formula: $$\hat{CV_a} = \sqrt{\frac{\sum_{i=1}^{n}CV_{A,i}^2}{n}}$$ where $CV_{A,i}$ is the age coefficient of variation for individual *i* [@cope_admitting_2007]. 

Lastly, additional information on the $L_0$ parameter was available from neonates sampled in Moreton Bay that were known to have a true age of zero, based on the presence of an unhealed umbilical scar. These individuals were included in the statistical model through the relationship $$L_{0,i} = L_0 + \epsilon \quad \quad \epsilon \sim N(0,\sigma_{L,i}^2)$$ where $L_{0,i}$ were the lengths of age zero individuals, and where $CV_L$ was again assumed proportional to length. The final model contained a total of six parameters, and estimation was undertaken using maximum likelihood with Template Model Builder [@kristensen_tmb:_2016].

Validation of growth using traditional techniques (e.g. fluorochrome chemical marking, centrum edge methods) was not possible due to small sample sizes and lack of suitable sampling across different months within years. Indirect validation of early growth was undertaken by comparing the fitted vertebral growth curve against monthly length frequency of neonate and young juvenile sharks in Moreton Bay. 

### Reproductive biology
The relationship between weight, *W*, and total length, *L*, was modelled using a power curve $W(L) = \beta_1\cdot L^{\beta_2}e^{\epsilon}$. Parameters $\beta_1$, $\beta_2$ and $\sigma$ were obtained using maximum likelihood estimation from the log-linear regression model $ln(W_i) = ln(\beta_1) + \beta_2\cdot ln(L_i) + \epsilon$, where $ln(\beta_1)$ and $\beta_2$ correspond to the intercept and slope, and where $\epsilon \sim N(0, \sigma^2)$ is a normally distributed random variable with variance $\sigma^2$. Sex and the interaction of sex and length were included as factors in the model to test whether weight-at-length differed between males and females. 

Maturity status was determined macroscopically using a three-stage classification of male clasper condition (C = 1-3) and a six-stage classification of female uterus condition (U = 1-6) (Table 1) [@walker_spatial_2007]. Maturity stage data were then converted to binary form (immature = 0, mature = 1) for statistical analysis. The relationship between maturity stage and length was determined using a Generalised Linear Model of the form $$ P_i \sim Bernoulli(p_i) \quad\quad p_i = logit(\beta_3 + \beta_4 L_i)^{-1}$$ where the probability of an individual being mature, $P_i$, was modelled as a Bernoulli random variable, and parameters $\beta_3$ and $\beta_4$ were estimated using maximum likelihood. The lengths at which 50% and 95% of the population was mature were further derived as: $$L_{50} = -\beta_3/\beta_4 \quad\quad L_{95}=\frac{1}{\beta_4}log(19)-\beta_3/\beta_4$$ Bootstrapping (*n* = 1000) was done on the derived parameters ($L_{50}$ and $L_{95}$) to estimate standard errors and calculate confidence intervals. Maturity analyses were undertaken for both sexes separately and combined, and also undertaken for age by substituting with length in the above equation. The male maturation process was further investigated by modelling the development of clasper length as a function of length (see Supplementary Material). 

For each analysis a graphical comparison was done for *C. tilstoni* using parameters estimated from previous studies [@stevens_biology_1986; @davenport_age_1988; @harry_age_2013], and using raw data presented in Harry *et al.* [-@harry_age_2013] for the Qld population (see Fig. 1 for location of previous studies). 

### Demographic analysis
Comparative population dynamics was investigated using an age- and sex-structured demographic model based on Lotka's generalized equation [@xiao_demographic_2000; @xiao_relationship_2002]:  $$1 = \int_{a_0}^{\infty}R(a)\beta(a)e^{\int_{a_0}^{a}\Lambda_{g, N}(s) ds}da$$ where $a$ is age (years) and $a_0$ = 0 is the age at birth, $R(a) = R$ is age-specific embryonic sex-ratio (assumed to be constant), $\beta(a)$ is age-specific female reproductive rate, and $\Lambda_{g, N}$ is the intrinsic rate of population decrease with age of sex *g* in numbers (year$^{-1}$). The age-specific female reproductive rate was further given by: $$\beta(a) = (\beta_5 + \beta_6 \cdot L_f(a)) \times P_{Max} \times (1 - exp( -ln(19)(\frac{a-A_{50}}{A_{95} - A_{95}})))^{-1}$$ where $\beta_5$ and $\beta_6$ are the intercept and slope of a linear regression of fecundity at length and where $P_{Max}$ is the proportion of females in the population that reproduce annually. 

$\Lambda_{g,N}$ can be solved numerically if $R(a)$ and $\beta(a)$ are known, and is a measure of the gross productivity of the population [@xiao_demographic_2000]. If female natural mortality at age, $M_f(a)$, is known and under the assumption of a stable age distribution, it is possible to calculate the intrinsic rate of population increase with time, $r$, or the net productivity of the population for both sexes and the gross productivity for males [@xiao_demographic_2000; @xiao_relationship_2002]: $$\Lambda_{f,N}(a) = -(r + M_f(a))$$ $$\Lambda_{m,N}(a) = -(r + M_m(a))$$

The stable age distribution of the population, the proportion of individuals of sex $g$, at age *a*, in biomass was calculated as:  $$p_{g, B}(a) = \frac{W_{g}(a)exp(\int_{a_0}^{a}\Lambda_{g, N}(s) ds)}{\int_{a_0}^{\infty}W_{g}(a)exp(\int_{a_0}^{a}\Lambda_{g, N}(s) ds)da}$$ The mean and variance of ages in the population, in biomass, were further calculated as: $$\mu = \int_{a_0}^{a}(a-a_0)p(a)da$$ and $$\sigma^2 = \int_{a_0}^{a}(a-a_0-\mu)p(a)da$$

The per-generation rate of multiplication, $R_0$, or number of daughters expected per female per lifetime, was calculated as: $$R_0 =\int_{a_0}^{\infty}R(a)\beta(a)e^{\int_{a_0}^{a}M_f(s) ds}da $$

All numerical integration and optimization required in the above equations was done using R [@rcoreteam_r:_2018]. 

The influence of uncertainty in demographic traits on net productivity ($r$) was investigated with Monte Carlo simulation [@cortes_incorporating_2002; @braccini_displaying_2015]. For each species the demographic analysis was repeated 1000 times using, where possible, weight, growth, and maturity parameters randomly drawn from a multivariate normal distribution. The mean and variance-covariance matrix of these distributions were obtained from each of the respective best fit models described above. Uncertainty in reproductive frequency was incorporated by drawing random values of $P_{Max}$ from a uniform distribution. A constant, size-based method was used to specify natural mortality $M_g(a)$ in the above equations [@then_evaluating_2015]: $$M_g = 4.118 \cdot K_g^{0.73} \cdot L_{\infty,g}^{-0.33}$$ Additional variability was added to the calculated value of $M_g$ in each simulation to ensure a wide range of values were considered. Values were drawn from a random normal distribution with a CV of $0.2M_g$. Additional details of the Monte Carlo simulation and choice of priors is supplied in the Supplementary Material.

Finally it was necessary to clarify two issues regarding interpretation of the above demographic method, namely 1) the rationale behind the choice of $M$, and 2) what the assumed population depletion was. As with most population models applied to fish, $M$ was central to interpretation but unknown. Many methods exist for calculating *M* ranging from purely theoretical to empirical [@kenchington_natural_2014; @then_evaluating_2015], however the choice of method is subjective. A common approach to dealing with this subjectivity is to average *M* over multiple methods, although Then *et al.* [-@then_evaluating_2015] advise against this. A further problem, as noted by Pardo *et al.* [-@pardo_maximum_2016], is that many of these methods are based on data for teleosts, and do not give reasonable values for sharks and rays. The second, interrelated issue is the amount of population depletion corresponding to the life history data used in the model [@cortes_perspectives_2016]. Since life history parameters change in response to population density [@romine_compensatory_2013; @taylor_unconfounding_2009], unless all components of the data were collected simultaneously and at a population size close to zero, the final value of $r$ is unlikely to reflect the maximum rate achievable, $r_m$. It is arguably $r_m$ that is of greatest interest to fishery managers [@pardo_maximum_2016]. 

One benefit of the formulation of the Euler-Lotka equation used in this study is the explicit link between $r$, $\Lambda_f$, and $M_f$ [@xiao_demographic_2000]. For a population to be viable (i.e. $r \geq 0$),  $M_f$ is restricted such that $0 \leq M_f \leq -\Lambda_f$. Assuming that density dependent changes in $r$ are predominantly mediated by changes in *M* [@smith_intrinsic_1998], then gross productivity of females, $\Lambda_f$, which is solely a function of reproductive characteristics and independent of *M*, effectively gives an upper bound for both $r$ and $M$. The decision to use the method by Then *et al.* [-@then_evaluating_2015] for calculating *M* was somewhat arbitrary, however it was one of the few methods that consistently led to plausible values for all populations. The values of *M* generated with this method were slightly higher than the method used by Pardo *et al.* [-@pardo_maximum_2016] in their comparative study of $r_m$ in sharks and rays. Nonetheless, since most values corresponded to > 90% annualised survival (see below), it would be reasonable to interpret them as close to the $r_m$ that would occur at low population density.

## Results
A total of `r nrow(data)` samples were available for life history analysis including `r table(data$Sex)[1]` females (`r min(data$STL[data$Sex == "Female"], na.rm = T) %>% round()` - `r max(data$STL[data$Sex == "Female"], na.rm = T)` cm) and `r table(data$Sex)[2]` males (`r min(data$STL[data$Sex == "Male"]) %>% round()` - `r max(data$STL[data$Sex == "Male"])` cm). Sharks from Moreton Bay were predominantly neonates and small juveniles up to `r max(data$STL[data$Source == "QLD: 2004 - 2007"],na.rm=T)` cm and were captured in an approximately equal sex ratio (Fig. 2). Sharks caught in northern NSW by the OTLF were predominantly > 150 cm TL, and there was a bias towards males, which made up `r round(nsw_sex_ratio[2]/sum(nsw_sex_ratio),2)*100`% of samples. Ninety percent of NSW samples were obtained from depths between 30 and 90 m, with males caught to a maximum depth of `r round(depth_max[2])` m, and females to `r round(depth_max[1])` m (Fig. S1). 

Of the `r table(data$Source)[3] + 1` individuals sampled from NSW between 2008 and 2010 and characterised using mtDNA and nDNA genotyping, 54 were identified as purebred *C. limbatus*. Sixteen individuals were hybrids that displayed a conflict between their mtDNA and nDNA. A further 36 individuals were identified as possible hybrids carrying one or more nuclear alleles from *C. tilstoni*. Finally, two individuals were unable to be identified and a single individual was identified as a purebred *C. tilstoni*. Like previous studies, all individuals with hybrid ancestry appeared to have a *C. limbatus* phenotype [@morgan_detection_2012; @harry_comparison_2012], consistent with a recent study indicating that hybrids are introgressed (J.A.T. Morgan, unpublished data). Hybrid individuals were included with the analysis of *C. limbatus* life history and the single purebred *C. tilstoni* was removed. 

### Age and growth
Distinct pairs of growth zones were visible in the corpus calcareum and, to a lesser extent, the intermedialia of sectioned vertebrae (Fig. S2). An age-bias plot showed discrepency between readers (Fig. S3), however it was not statistically significant (Bowkers test of symmetry: $\chi^2$ =  `r signif(summary(age_bias, what = "Bowker")[[3]],4)`, d.f. = `r summary(age_bias, what = "Bowker")[[2]]`, *P* = `r signif(summary(age_bias, what = "Bowker")[[4]],4)`). Mean inter-reader CV was `r  age_precision$ACV %>% signif(2)` %. On this basis an acceptable and reproducible interpretation was considered to have been achieved, and further analyses proceeded under the assumption that each pair of growth zones corresponded to an annual increment. 

Vertebrae sections were available from a total of `r sum(age_stats$n)` individuals. Females (n = `r age_stats$n[1]`, `r paste(age_stats$minSTL[1], age_stats$maxSTL[1], sep=" - ")` cm) ranged in age from `r age_stats$minAge[1]*12` months to `r round(age_stats$maxAge[1])` years. Males (n = `r age_stats$n[2]`, `r paste(age_stats$minSTL[2], age_stats$maxSTL[2], sep=" - ")` cm) ranged in age from `r age_stats$minAge[2]*12` months to `r round(age_stats$maxAge[2])` years. A further `r length(len0$STL)` neonates collected in Moreton Bay were used for estimation of the $L_0$ parameter. 

Growth of male and female *C. limbatus* was similar until around three years of age (Figs 3a-b and 3e) after which females had a greater average length at age than males. Although absolute female growth rate exceeded that of males, females attained a larger asymptotic length (Table 2), and consequently *K* was greatest for males. While males attained a greater maximum age than females, this possibly reflects the smaller sample sizes for females. The use of a CV proportional to length resulted in a good fit to the data, as evident from the prediction intervals for length at age data (Figs. 3 a & b) and empirical $L_0$ observations (Fig. 3c). Variability in length, $CV_L$, averaged `r round(rep$par.fixed[6] * 100, 1)` % of length (Table 2, Fig. 3d). 

Monthly length measurements from a *C. limbatus* nursery area in Moreton Bay appeared to show distinct groupings corresponding to cohorts from 0+ to 2+ years, most evident in October and November. Neonates with open umbilical scars first appeared in Moreton Bay during early November, at which time they were clearly separable from the 0+ and 1+ cohorts (Fig. 3f). A further seven individuals that were larger again were thought to belong to the 2+ cohort. In comparison to the growth curve fit to vertebral ages, sharks within Moreton Bay appeared to grow slower (Fig. 3f).

### Reproductive biology
Weight measurements were obtained from `r weight_stats$n[1]` females and `r weight_stats$n[2]` males (Fig. 4a). The heaviest female and male weighed `r weight_stats$maxWgt[1]` kg and `r weight_stats$maxWgt[2]` kg, respectively. Although the heaviest individual was a male, no large (> 240 cm) or pregnant females were weighed, and it is likely they would exceed the weight of males of equivalent length. Neither sex nor the interaction of sex and length were statistically significant (ANOVA: d.f. = 2, `r anova_lw$Res.Df[2]`, F = `r signif(anova_lw$F[2], 4)`, *P* = `r signif(anova_lw[2,6],4)`) (Fig. 4b, Table 2).

Maturity stage was recorded for `r sum(female_mat_stats$n)` females; the majority (n = `r sum(female_mat_stats$n[1:2])`) of these were immature, most of which were neonates sampled from Moreton Bay. The largest and oldest immature females (U = 1-2) were `r max(female_mat_stats$maxSTL[1:2])` cm and `r round(max(female_mat_stats$maxAge[1:2]))` years, respectively, while the smallest and youngest mature females (U = 3-6) were `r min(female_mat_stats$minSTL[3:5])` cm and `r round(min(female_mat_stats$minAge[3:5]))` years, respectively. Maturity stage was recorded for `r sum(male_mat_stats$n)` males. The largest and oldest immature males (C = 1-2) were `r max(male_mat_stats$maxSTL[1:2])` cm and `r round(max(male_mat_stats$maxAge[1:2]))` years, respectively, while the smallest and youngest mature males (C = 3) were `r min(male_mat_stats$minSTL[3])` cm and `r round(min(male_mat_stats$minAge[3]))` years, respectively. For both age and length, neither sex, nor the interaction with sex was statistically significant (Analysis of deviance - length: $\chi$ = `r signif(anova_lm$Deviance[2],4)`, d.f. = 2, *P* = `r signif(anova_lm[2,5],4)`; Analysis of deviance - age: $\chi$ = `r signif(anova_am$Deviance[2],4)`, d.f. = 2, *P* = `r signif(anova_am[2,5],4)`, Fig. 5a-b, Table 2). Due to the small sample size of mature females, it was not possible to model maternal condition and assess the length and age at which reproduction begins. Male clasper development was minimal until around 150 cm. Beyond this length claspers began to elongate, reaching $CL_{50}$ at `r round(coef(clasp_mod)[3])` cm, around the same length as maturity occurred (Fig. S4). Unlike *C. tilstoni*, clasper length did not reach a well-defined asymptotic length. 

Only `r female_mat_stats$n[4]` of the `r sum(female_mat_stats$n[3:5])` mature females (U = 3-6), were pregnant (Table 3), so limited inferences could be made about the timing and frequency of the reproductive cycle. Pregnant females included three individuals at a similar stage of embryonic development with an overall mean embryo length of `r round(mean(pregnant$EmbTL[-1])/10, 1)` cm during April, and another in June with a mean embryo length of `r pregnant$EmbTL[1]/10` cm. Mean fecundity of females was `r mean(pregnant$Emb)` pups, and ranged from `r min(pregnant$Emb)` to `r max(pregnant$Emb)`. The mean ($\pm$ s.d.) length of `r length(len0$STL)` neonates from Moreton Bay was `r signif(mean(len0$STL), 4)` $\pm$ `r signif(sd(len0$STL), 3)` cm. The mean ($\pm$ s.d.) weight of `r L0_weight$n` neonates was `r signif(L0_weight$mean_Wgt, 4)` $\pm$ `r signif(L0_weight$sd_Wgt, 3)` kg.

In the four years that samples were collected from  Moreton Bay, neonates were present from early November to early February, suggesting *C. limbatus* has a synchronous reproductive cycle with a three-month pupping season from November to January. Four post-partum (U = 6) females were also recorded between April and June. This conflicted with other evidence suggestive of a synchronous reproductive cycle and it was thought these females might have aborted their young upon capture or been assigned an incorrect uterus stage. The fraction of mature females that were pregnant was `r round(female_mat_stats$n[4]/sum(female_mat_stats$n[3:5]), 2)*100`%, or `r round(sum(female_mat_stats$n[c(4,5)])/sum(female_mat_stats$n[3:5]), 2)*100`% if U = 6 females were included. Although it was not possible to determine the duration and frequency of reproduction, the large proportion of non-pregnant (U = 3) females observed suggests that it is likely to be a minimum of two years in duration or even longer. 

### Demographic analysis
Gross population productivity of females, $\Lambda_f$, was highest for *C. tilstoni*, with mean values for the NT `r  (max(-demog_summary$Lambda_f_mean) / -demog_summary$Lambda_f_mean[2] - 1) %>% round(2) * 100` % higher than that of Qld and `r   (max(-demog_summary$Lambda_f_mean) / min(-demog_summary$Lambda_f_mean) - 1) %>% round(2) * 100`% higher than *C. limbatus* (Table 4). Holding all other variables equal, the range of possible values for $M_f$ are thus $0 \leq M_f \leq -\Lambda_f$, for a population to be viable ($r \geq 0$). Values for $M_f$ predicted from the size-based method were within the lower half of plausible values (Fig. 6b); mean annualised survival ($e^{-M_f}$) ranged from `r exp(-min(demog_summary$M_f_mean)) %>% round(2) * 100` % in *C. limbatus* to `r exp(-max(demog_summary$M_f_mean)) %>% round(2) * 100`% in NT *C. tilstoni*. Due to the high CV specified, a wide range of values were nonetheless included in the Monte Carlo simulation (Fig. 6a). In line with its higher $M$, net productivity, $r$, was higher for *C. tilstoni* (Fig. 6b). The net productivity of the NT population was `r  (max(demog_summary$r_int_mean) / demog_summary$r_int_mean[2] - 1) %>% round(2) * 100` % higher than Qld and `r  (max(demog_summary$r_int_mean) / min(demog_summary$r_int_mean) - 1) %>% round(2) * 100`% higher than *C. limbatus*. Reproductive output, $R_0$, was variable across all species, and highest on average for Qld *C. tilstoni* with females producing, on average, 12 female pups during their life. 

Due to their smaller $L_\infty$ and higher $K$ (Table 2), average $M$ calculated using the size-based method was higher for males than females (Table 4). This translated to annualised male survival being `r min(m_ratios$percents)`% lower in *C. limbatus* and `r max(m_ratios$percents)`% lower in *C. tilstoni*. Accordingly, the mean age of the population in numbers and biomass was always greater in females than males (Fig. 6c, Table 4). Mean age in both *C. tilstoni* populations was 3 to 4 years, or 5 to 7 years if weighted by biomass. Mean age in the *C. limbatus* population was c. 5 years, or c. 10 years if weighted by biomass. As a result of this difference, biomass in *C. limbatus* populations is predominantly concentrated in lengths greater than the maximum size of *C. tilstoni* (Fig. 6d). 


## Discussion

### Life history of *C. limbatus*
This study is the first detailed description of the life history of *C. limbatus* from Australian waters, where information has previously been difficult to obtain due to its co-occurrence with the morphologically similar *C. tilstoni*. Aspects of the life history of *C. limbatus* have previously been studied in many parts of its range including the northwest Atlantic [@castro_biology_1996], South Africa [@dudley_sharks_1993; @wintner_age_1996], Indonesia [@white_catch_2007; @smart_age_2015], Senegal [@capape_reproductive_2004], and, most comprehensively, the Gulf of Mexico [@branstetter_age_1987; @killam_age_1989; @carlson_differences_2006; @tovar-avila_edad_2009; @passerotti_updates_2012; @baremore_reproduction_2013]. Generally speaking, Australian *C. limbatus* has life history characteristics least similar to populations in the Gulf of Mexico and northwest Atlantic (GOM and NWA), which are characterised by smaller maximum lengths that rarely exceed 200 cm. Empirical maximum lengths from the present study demonstrate that in Australian waters both sexes regularly exceed 250 cm. This is somewhat larger still than populations off South Africa, Indonesia, and Senegal where maximum lengths of 245 to 247 cm were recorded [@capape_reproductive_2004; @dudley_sharks_1993; @white_catch_2007]. The heaviest male from this study (`r data$STL[which(data$Wgt == max(data$Wgt, na.rm=T))]`cm) weighed `r max(data$Wgt, na.rm=T)` kg and the largest female (`r data$STL %>% max(na.rm = T)`cm) was predicted to weigh between `r largest_lower` and `r largest_upper` kg (Fig. 4a). A 221 cm, 122 kg mature non-pregnant (U = 3) female captured in a Qld recreational fishing tournament appears to be the heaviest measured specimen both in Australia and globally [@salini_northern_2007]. 

Conclusive validation of growth has not yet been achieved for any *C. limbatus* population. Growth estimates from independent vertebral ageing studies in the Gulf of Mexico have consistently been similar [@carlson_differences_2006; @tovar-avila_edad_2009; @passerotti_updates_2012], providing some confidence that vertebral growth zones in this species reflect age. No validation was possible in the current study although a visual comparison of the monthly length structure from Moreton Bay suggested a slightly slower growth than was estimated from vertebral sections. Lengths at age of *C. limbatus* off central eastern Australia were intermediate to South African and Indonesian populations [@wintner_age_1996; @smart_age_2015]. However, noting that each of these studies are unvalidated and based on small sample sizes, it is probably unwise to read any biological significance into differences among those populations. Incorrect interpretation of the first growth increment or a single early growth zone could explain the difference between studies. The oldest individuals in this study were a `r max(age_stats$maxAge) %>% round()` year old male and a `r min(age_stats$maxAge) %>% round()` year old female. These maximum ages were similar to the oldest  *C. limbatus* aged from the GOM [@passerotti_updates_2012], a 23.5 year old male. Noting the potential for age underestimation in shark and ray ageing studies [@harry_evidence_2018], it is possible that *C. limbatus* in all populations live longer than currently recognised. 

The growth modeling approach in the current study involved adapting the model of Cope and Punt [-@cope_admitting_2007]. A key feature of their model is the explicit incorporation of ageing error as a random effect. This is a useful addition for sharks and rays, which can be difficult to age [@goldman_assessing_2012]. In this study the model was changed to incorporate two relevant features of *C. limbatus* biology. Firstly, it was fit to both sexes simultaneously. This avoided unnecessarily estimating sex-specific parameters for $L_0$, which was the same for both sexes. It also avoided estimating a sex-specific variance parameter, which was assumed not to differ between sexes either. Secondly, empirical data on $L_0$ were included in the statistical model itself, and used to estimate $L_0$ with vertebral ageing data jointly. This approach removes the potential bias in parameter estimates caused by the more common approach of fixing $L_0$ at a known value [@pardo_avoiding_2013]. 

With few pregnant females sampled and no data collected on ovarian follicles, many aspects of reproduction remain uncertain for central eastern Australian *C. limbatus*. The seasonal occurrence of large numbers of neonates in Moreton Bay between November and February [@taylor_size_2013] indicates that reproduction is synchronous and occurs in summer, as is typical throughout its range [@fourmanoir_requins_1961; @simpfendorfer_utilisation_1993; @castro_shark_1993]. Less is known about the frequency of reproduction. Within both the GOM and NWA, *C. limbatus* reproduces biennially [@castro_biology_1996; @baremore_reproduction_2013]. Capape *et al.* [-@capape_reproductive_2004] also speculated that *C. limbatus* had a biennial reproductive cycle off Senegal. Off South Africa, patterns in development of ovarian follicles sampled from 260 mature females supported a three year reproductive cycle [@dudley_sharks_1993]. The high proportion of mature, non-pregnant females in this study area indicates that reproduction is at least biennial and likely longer. This would be consistent with other large congeners such as dusky, *Carcharhinus obscurus* [@dudley_sharks_2005], and sandbar, *Carcharhinus plumbeus*, sharks [@baremore_reproduction_2012]. Alternatively, sampling limitations including spatial, temporal and gear selectivity effects might have contributed to the low proportion of pregnant females observed. 

Despite limited data, the average fecundity of 6.6 calculated in this study is consistent with other populations that attain a similar maximum size. Mean and median litter sizes of 6.7 and 6, respectively, were reported in two studies off South Africa, where litter sizes ranged from 1 to 11 [@bass_sharks_1973; @dudley_sharks_1993]. In Indonesia, mean litter size was 6.6 and ranged from 2 to 10 [@white_catch_2007], while off Senegal, mean litter size was 6.8 and ranged from 1 to 8 [@cadenat_requins_1981; @capape_reproductive_2004]. Variability in length at birth is well documented in *C. limbatus* [@garrick_sharks_1982; @harry_comparison_2012]. Australian *C. limbatus* are born at a slightly longer length to other global populations, although length and weight at birth was similar to the single full-term litter measured off South Africa [@dudley_sharks_1993]. Harry *et al.* [-@harry_comparison_2012] speculated that this larger length could be a way of reducing competition with *C. tilstoni*, which co-occurs in some nursery areas within Australia [@simpfendorfer_utilisation_1993]. 

Length at maturity in Australian waters appears to be most similar to South Africa, where both sexes mature at > 200 cm, although robust comparison between studies is not possible due to methodological differences [@dudley_sharks_1993]. While male and female *C. limbatus* in Australian waters probably differ in their length and age at maturity, data were insufficient to demonstrate this using statistical hypothesis testing, nor were there sufficient data to determine when females begin to reproduce. Baremore and Passerotti [-@baremore_reproduction_2013], who examined length at maternity of *C. limbatus* in the GOM, found that 50% of females were in maternal condition at 10.1 years. Based on the age at maturity of c. 8 years and a two to three year reproductive cycle, it is unlikely that females would start contributing to population recruitment before age 10 off central eastern Australia. 

Additional notes on the ecology of *C. limbatus* are provided in the Supplementary Material. 

### Comparative demography of *C. limbatus* and *C. tilstoni*
This study confirms that the co-occurring *C. limbatus* and *C. tilstoni* differ substantially in many aspects of their life histories, despite their morphological similarities. At birth, *C. limbatus* are approximately the same size as one year old *C. tilstoni* (Figs 3 a & b). Length at age between species further diverges over ontogeny with *C. limbatus* remaining larger, on average, throughout life (Fig. 3f). Although weight at length is similar between species (Fig. 4b), there are large differences in maximum body size, with the heaviest *C. limbatus* more than three times the weight of the heaviest *C. tilstoni*. Maturation of *C. limbatus* begins at lengths well above the maximum length attained by *C. tilstoni* (Fig. 5c), which also matures and reproduces at a younger age (Fig. 5d). The larger *C. limbatus* has a higher mean fecundity (Table 2), but likely reproduces less frequently. Based on a long-term tagging study, *C. tilstoni* is known to live to at least 20 years [@last_sharks_2009; @harry_age_2013]. Vertebral ageing from this study suggested *C. limbatus* live to 24 years. Given their substantially larger size and likely lower mortality, as well as the potential for age underestimation [@harry_evidence_2018], it is reasonable to surmise that *C. limbatus* lives longer than *C. tilstoni*. 

Differences in life history between the Qld and NT *C. tilstoni* populations are summarised in Harry *et al.* [-@harry_age_2013]. While many aspects of their biology are similar, Harry *et al.* [-@harry_age_2013] found that the Qld population matured at an older age and larger size. Growth of the NT population was faster than Qld and, although not reflected in growth parameters, the Qld population attains a slightly larger length. Since fecundity is proportional to length and length at birth is similar between populations, the lower average fecundity of the NT population is likely a result of mature females being smaller, on average, than those from Qld. 

The values of $r$ calculated in this study suggest that both *C. limbatus* and *C. tilstoni* are moderately productive species relative to other sharks and rays [@simpfendorfer_bright_2017]. Relative to each other however, *C. tilstoni* has a much higher productivity than *C. limbatus*, meaning these species are likely to differ in their response to exploitation. Further confounding these differences are the divergent size structures of the two species. When biomass is plotted against length, the fundamental differences between the life histories of the two species become particularly apparent (Fig. 6d). Whereas the smaller *C. tilstoni* completes its entire life cycle within nearshore and coastal habitats, this habitat is used only transitionally by *C. limbatus* as juveniles, with the majority of the population biomass occurring further offshore. 

These differences in demography have important implications for the numerous fisheries that capture this species complex within Australian waters and should be considered in the formulation of appropriate management strategies. For  size-selective gillnet fisheries capturing these species, it is evident that the majority of the *C. limbatus* biomass will be less vulnerable to fishing. Viewed in the historical context, large-scale, historical exploitation by the Taiwanese fleet would probably have had minimal impact on the adult biomass of *C. limbatus*, perhaps explaining the species' increase in relative abundance in the subsequent decades [@ovenden_towards_2010]. Likewise, the impacts of management measures such as size limits will affect each species differently. For example, in Qld where sharks are often captured by recreational fishers [@lynch_implications_2010], the upper size limit of 1.5m for this sector would presumably be ineffective at reducing mortality on *C. tilstoni* and effective for *C. limbatus*. Thus, despite the latter being inherently more susceptible to exploitation, *C. tilstoni* will likely have a greater exposure to inshore mixed-species fisheries. 

At present, all Australian jurisdictions report *C. tilstoni* and *C. limbatus* together. Morphological similarities aside, there is little, if any, justification for such grouping. Given the likely divergent responses to exploitation of the two species, it is likely that any inferences from catch or catch rates would be invalid, masking underlying population trends. Currently, exploitation of blacktip shark is low across northern Australia, however historically all regions and stocks have sporadically experienced periods of high catch driven by cyclical market trends. Any future attempts to develop these resources should acknowledge the differences between these species and ensure appropriate management measures are in place that include routine monitoring of relative abundance.

## Acknowledgements
The authors are indebted to the efforts of the Qld and NSW commercial shark fishers who enabled this research, as well as the scientific observers and laboratory staff from the NSW Department of Primary Industries who assisted in sample collection and analysis. Thank you to DS Waltrick and LFN Waltrick for your support and encouragement. This research was carried out using pre-existing data from completed research projects and as such did not receive any specific funding. 

## Conflicts of Interest
The authors declare no conflicts of interest.

\newpage

## References
